version: '3'
services:

    php:
        build:
            context: ./docker/php
        env_file:
            - .env
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./public:/var/www/public

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=StrongPassword
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./public:/var/www/public

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_HOST=${DB_HOST}

    maildev:
        image: djfarrelly/maildev
        ports:
            - ${MAILDEV_PORT}:80
